//
// IstanzaNumeroRosso.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IstanzaNumeroRosso: Codable { 


    public var idIstanza: String?
    public var tipoIstanza: String?
    public var risposteNonLette: Bool?
    public var dataCreazione: Date?
    public var dataRichiesta: Date?
    public var evidOpId: Int64?
    public var evidNrDUpd: Date?
    public var evidNrDUpdMigRv: Date?
    public var ageCAge: String?
    public var nomeAgente: String?
    public var cognomeAgente: String?
    public var telefonoAgente: String?
    public var codiceAreaAgente: String?
    public var descrAreaAgente: String?
    public var codicePoloAgente: String?
    public var descrPoloAgente: String?
    public var codiceMediolanumCliente: String?
    public var codiceCliente: String?
    public var nomeCliente: String?
    public var cognomeCliente: String?
    public var clusterClienteInforete: String?
    public var clusterClienteNumRosso: String?
    public var descrClusterCliente: String?
    public var codTipoProdotto: String?
    public var descrProdotto: String?
    public var numeroProdotto: String?
    public var stato: String?
    public var serverCReplica: String?
    public var testoDomanda: String?
    public var isIstanzaInterna: String?
    public var canale: String?
    public var idConversazione: String?
    public var idIstanzaPadre: String?
    public var cValoreDeroga: Int64?
    public var importo: Int64?
    public var durata: Int64?
    public var tipoStrumento: String?
    public var stimaOperazioni: Int64?
    public var tipoRichiesta: String?
    public var flagCliSens: String?
    public var valutazione: String?
    public var noteStaff: String?
    public var statoDeroga: String?
    public var canaleOpereazione: String?
    public var destinazione: String?
    public var noteSede: String?
    public var dataInoltro: Date?
    public var ageCAgeStaff: String?
    public var fPrivateBanker: String?
    public var ageCAgeDimesso: String?
    public var noteCliSensibile: String?
    public var fondo: String?
    public var compartoFondoIta: String?
    public var doubleChance: String?
    public var pianoVersamento: String?
    public var agevCommPac: String?
    public var classe: String?
    public var pctAgevRichiesta: String?
    public var cCliRilevante: String?
    public var cMotivoRichiesta: String?
    public var ageCAgeValutatore: String?
    public var impAgevComm: Int64?
    public var fValutatoFbNonCoperto: String?
    public var flgAutovalutata: String?
    public var codiceConvenzione: String?
    public var nacCProd: String?
    public var bondEdition: String?
    public var dtRiconciliazione: Date?
    public var fEsitoRiconciliazione: String?
    public var dtInvioSedeFt: Date?
    public var codiceAreaTerritoriale: Int64?
    public var tipoTrasferimento: String?
    public var picProgrammato: String?
    public var dtSottoscrizione: Date?
    public var importoSottoscrizione: Int64?
    public var codOperzDispBmed: String?
    public var tipoOperazione: String?
    public var argomento: String?
    public var risposte: [RispostaNumeroRosso]?

    public init(idIstanza: String?, tipoIstanza: String?, risposteNonLette: Bool?, dataCreazione: Date?, dataRichiesta: Date?, evidOpId: Int64?, evidNrDUpd: Date?, evidNrDUpdMigRv: Date?, ageCAge: String?, nomeAgente: String?, cognomeAgente: String?, telefonoAgente: String?, codiceAreaAgente: String?, descrAreaAgente: String?, codicePoloAgente: String?, descrPoloAgente: String?, codiceMediolanumCliente: String?, codiceCliente: String?, nomeCliente: String?, cognomeCliente: String?, clusterClienteInforete: String?, clusterClienteNumRosso: String?, descrClusterCliente: String?, codTipoProdotto: String?, descrProdotto: String?, numeroProdotto: String?, stato: String?, serverCReplica: String?, testoDomanda: String?, isIstanzaInterna: String?, canale: String?, idConversazione: String?, idIstanzaPadre: String?, cValoreDeroga: Int64?, importo: Int64?, durata: Int64?, tipoStrumento: String?, stimaOperazioni: Int64?, tipoRichiesta: String?, flagCliSens: String?, valutazione: String?, noteStaff: String?, statoDeroga: String?, canaleOpereazione: String?, destinazione: String?, noteSede: String?, dataInoltro: Date?, ageCAgeStaff: String?, fPrivateBanker: String?, ageCAgeDimesso: String?, noteCliSensibile: String?, fondo: String?, compartoFondoIta: String?, doubleChance: String?, pianoVersamento: String?, agevCommPac: String?, classe: String?, pctAgevRichiesta: String?, cCliRilevante: String?, cMotivoRichiesta: String?, ageCAgeValutatore: String?, impAgevComm: Int64?, fValutatoFbNonCoperto: String?, flgAutovalutata: String?, codiceConvenzione: String?, nacCProd: String?, bondEdition: String?, dtRiconciliazione: Date?, fEsitoRiconciliazione: String?, dtInvioSedeFt: Date?, codiceAreaTerritoriale: Int64?, tipoTrasferimento: String?, picProgrammato: String?, dtSottoscrizione: Date?, importoSottoscrizione: Int64?, codOperzDispBmed: String?, tipoOperazione: String?, argomento: String?, risposte: [RispostaNumeroRosso]?) {
        self.idIstanza = idIstanza
        self.tipoIstanza = tipoIstanza
        self.risposteNonLette = risposteNonLette
        self.dataCreazione = dataCreazione
        self.dataRichiesta = dataRichiesta
        self.evidOpId = evidOpId
        self.evidNrDUpd = evidNrDUpd
        self.evidNrDUpdMigRv = evidNrDUpdMigRv
        self.ageCAge = ageCAge
        self.nomeAgente = nomeAgente
        self.cognomeAgente = cognomeAgente
        self.telefonoAgente = telefonoAgente
        self.codiceAreaAgente = codiceAreaAgente
        self.descrAreaAgente = descrAreaAgente
        self.codicePoloAgente = codicePoloAgente
        self.descrPoloAgente = descrPoloAgente
        self.codiceMediolanumCliente = codiceMediolanumCliente
        self.codiceCliente = codiceCliente
        self.nomeCliente = nomeCliente
        self.cognomeCliente = cognomeCliente
        self.clusterClienteInforete = clusterClienteInforete
        self.clusterClienteNumRosso = clusterClienteNumRosso
        self.descrClusterCliente = descrClusterCliente
        self.codTipoProdotto = codTipoProdotto
        self.descrProdotto = descrProdotto
        self.numeroProdotto = numeroProdotto
        self.stato = stato
        self.serverCReplica = serverCReplica
        self.testoDomanda = testoDomanda
        self.isIstanzaInterna = isIstanzaInterna
        self.canale = canale
        self.idConversazione = idConversazione
        self.idIstanzaPadre = idIstanzaPadre
        self.cValoreDeroga = cValoreDeroga
        self.importo = importo
        self.durata = durata
        self.tipoStrumento = tipoStrumento
        self.stimaOperazioni = stimaOperazioni
        self.tipoRichiesta = tipoRichiesta
        self.flagCliSens = flagCliSens
        self.valutazione = valutazione
        self.noteStaff = noteStaff
        self.statoDeroga = statoDeroga
        self.canaleOpereazione = canaleOpereazione
        self.destinazione = destinazione
        self.noteSede = noteSede
        self.dataInoltro = dataInoltro
        self.ageCAgeStaff = ageCAgeStaff
        self.fPrivateBanker = fPrivateBanker
        self.ageCAgeDimesso = ageCAgeDimesso
        self.noteCliSensibile = noteCliSensibile
        self.fondo = fondo
        self.compartoFondoIta = compartoFondoIta
        self.doubleChance = doubleChance
        self.pianoVersamento = pianoVersamento
        self.agevCommPac = agevCommPac
        self.classe = classe
        self.pctAgevRichiesta = pctAgevRichiesta
        self.cCliRilevante = cCliRilevante
        self.cMotivoRichiesta = cMotivoRichiesta
        self.ageCAgeValutatore = ageCAgeValutatore
        self.impAgevComm = impAgevComm
        self.fValutatoFbNonCoperto = fValutatoFbNonCoperto
        self.flgAutovalutata = flgAutovalutata
        self.codiceConvenzione = codiceConvenzione
        self.nacCProd = nacCProd
        self.bondEdition = bondEdition
        self.dtRiconciliazione = dtRiconciliazione
        self.fEsitoRiconciliazione = fEsitoRiconciliazione
        self.dtInvioSedeFt = dtInvioSedeFt
        self.codiceAreaTerritoriale = codiceAreaTerritoriale
        self.tipoTrasferimento = tipoTrasferimento
        self.picProgrammato = picProgrammato
        self.dtSottoscrizione = dtSottoscrizione
        self.importoSottoscrizione = importoSottoscrizione
        self.codOperzDispBmed = codOperzDispBmed
        self.tipoOperazione = tipoOperazione
        self.argomento = argomento
        self.risposte = risposte
    }

}
