//
// IstanzaResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct IstanzaResponse: Codable { 


    public var data: IstanzaNumeroRosso?
    public var result: MedMapApiResponseResult?

    public init(data: IstanzaNumeroRosso?, result: MedMapApiResponseResult?) {
        self.data = data
        self.result = result
    }

}
