//
// MedMapApiResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MedMapApiResponseResult: Codable { 


    public var messages: [MedMadMessage]?
    public var warnings: [MedMadMessage]?

    public init(messages: [MedMadMessage]?, warnings: [MedMadMessage]?) {
        self.messages = messages
        self.warnings = warnings
    }

}
