//
// NotificaLettura.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NotificaLettura: Codable { 


    public var letto: Bool?

    public init(letto: Bool?) {
        self.letto = letto
    }

}
