//
// Problem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Problem: Codable { 


    /** An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).  */
    public var type: String? = "about:blank"
    /** A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable  */
    public var title: String?
    /** The HTTP status code generated by the origin server for this occurrence of the problem.  */
    public var status: Int?
    /** A human readable explanation specific to this occurrence of the problem.  */
    public var detail: String?
    /** An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
    public var instance: String?

    public init(type: String?, title: String?, status: Int?, detail: String?, instance: String?) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
    }

}
