//
// RispostaNumeroRosso.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RispostaNumeroRosso: Codable { 


    public var idRisposta: String?
    public var evidNrDLettura: Date?
    public var dataRisposta: Date?
    public var stato: String?
    public var tipoRisposta: String?
    public var numeroIstanza: String?
    public var serverCReplica: String?
    public var testoRisposta: String?
    public var dataLettura: Date?
    public var operatore: String?
    public var idRecord: String?
    public var statoRichiesta: String?
    public var ageCAgeOperatore: String?

    public init(idRisposta: String?, evidNrDLettura: Date?, dataRisposta: Date?, stato: String?, tipoRisposta: String?, numeroIstanza: String?, serverCReplica: String?, testoRisposta: String?, dataLettura: Date?, operatore: String?, idRecord: String?, statoRichiesta: String?, ageCAgeOperatore: String?) {
        self.idRisposta = idRisposta
        self.evidNrDLettura = evidNrDLettura
        self.dataRisposta = dataRisposta
        self.stato = stato
        self.tipoRisposta = tipoRisposta
        self.numeroIstanza = numeroIstanza
        self.serverCReplica = serverCReplica
        self.testoRisposta = testoRisposta
        self.dataLettura = dataLettura
        self.operatore = operatore
        self.idRecord = idRecord
        self.statoRichiesta = statoRichiesta
        self.ageCAgeOperatore = ageCAgeOperatore
    }

}
