//
// Warnings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Warnings: Codable { 


    public var messages: String?

    public init(messages: String?) {
        self.messages = messages
    }

}
